cluster.name: "elk"
network.host: ${ES_PUBLIC_HOST} # Для корректной работы внутри контейнера

xpack.security.enabled: false # Для поддержки функционала, обеспечивающего безопасность кластера
xpack.license.self_generated.type: basic # Типа лицензии "basic" для наших нужд хватит с головой